// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_37m4IFPMwBfB5i9ReC_XruaR55bmans',
    appId: '1:586068989468:web:b4fb49c1e0db27a8d6f1d9',
    messagingSenderId: '586068989468',
    projectId: 'tiktok-challenge-cskim',
    authDomain: 'tiktok-challenge-cskim.firebaseapp.com',
    storageBucket: 'tiktok-challenge-cskim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZFBssumDQ1hsQfdIwA1ca2jymM3Haks',
    appId: '1:586068989468:android:4a8771f569ac450dd6f1d9',
    messagingSenderId: '586068989468',
    projectId: 'tiktok-challenge-cskim',
    storageBucket: 'tiktok-challenge-cskim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfoEtJbS-wD8CPHeGCVBhKZ9S6W7eBS4',
    appId: '1:586068989468:ios:40010c8be1b5d092d6f1d9',
    messagingSenderId: '586068989468',
    projectId: 'tiktok-challenge-cskim',
    storageBucket: 'tiktok-challenge-cskim.appspot.com',
    iosBundleId: 'com.example.nomadcodersFlutterChallenge',
  );

}