final dummyInterests = [
  'Fashion & beauty',
  'Outdoors',
  'Arts & culture',
  'Animation & comics',
  'Business & finance',
  'Food',
  'Travel',
  'Entertainment',
  'Music',
  'Gaming',
  'Fashion & beauty 2',
  'Outdoors 2',
  'Arts & culture 2',
  'Animation & comics 2',
  'Business & finance 2',
  'Food 2',
  'Travel 2',
  'Entertainment 2',
  'Music 2',
  'Gaming 2',
];

final dummyMusicInterests = [
  'Rap',
  'R&B & Soul',
  'Grammy Awards',
  'Pop',
  'K-pop',
  'Music industry',
  'EDM',
  'Music news',
  'Hip hop',
  'Reggae',
];

final dummyEntertainmentInterets = [
  'Anime',
  'Movies & TV',
  'Harry Potter',
  'Marvel Universe',
  'Movie news',
  'Naruto',
  'Movies',
  'Grammy Awards',
  'Entertainment',
];
